#!/usr/bin/env bash

exec 2>&1

cd "{{pkg.svc_path}}"

# additional script, custom to fetch vsb.ipxe, coreos image, etc..
[[ -f "{{pkg.svc_config_path}}/init.sh" ]] && bash {{pkg.svc_config_path}}/init.sh {{ pkg.svc_data_path }}
[[ -f "{{pkg.svc_config_path}}/vsb.ipxe" ]] && cp {{pkg.svc_config_path}}/vsb.ipxe {{ pkg.svc_data_path }}

