
# vesbox-ipxe is wraps nginx plan, it adds hooks & scripts to configure content for iPXE boot

## VES iPXE configuration, None
# behaviour is delivered through config/init.sh script and config/vsb.ipxe

## NGINX configuration
worker_processes = 4

[ves]
image_revision = "" # empty = latest fetched


[events]
worker_connections = 1024

[http]
sendfile = "on"
tcp_nopush = "on"
tcp_nodelay = "on"
keepalive_timeout = 60

[http.listen]
port = 8080

[http.server]
server_name = "vesbox-ipxe"
fqdn = "172.16.4.51" # keep ip here, as long as its used for live-boot httpfs/fetch option

